name: chrysant
description: "A restaurant management system, written with Flutter."
publish_to: 'none'

version: 0.2.0

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  flutter_styled_toast: ^2.2.1
  riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  responsive_sizer: ^3.2.0
  isar: ^3.1.0+1
  build_runner: ^2.4.7
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  logger: ^2.0.2+1
  riverpod_generator: ^2.3.9
  dropdown_button2: ^2.3.9
  riverpod_annotation: ^2.3.3
  image_picker: ^1.0.5
  text_scroll: ^0.2.0

dev_dependencies:
  dependency_validator: ^3.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
