name: chrysant
description: "A restaurant management system, written with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  flutter_styled_toast: ^2.2.1
  riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.9
  responsive_sizer: ^3.2.0
  isar: ^3.1.0+1
  build_runner: ^2.4.7
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  logger: ^2.0.2+1
  riverpod_generator: ^2.3.9
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
